#ifndef REMODMAN_MANAGER_DEFINITIONS_INCLUDED
#define REMODMAN_MANAGER_DEFINITIONS_INCLUDED

#pragma once

#ifndef REMM_MODS_FOLDER
    #define REMM_MODS_FOLDER "/Mods/"
#endif  // REMM_MODS_FOLDER

#ifndef REMM_DOWNLOADS_FOLDER
    #define REMM_DOWNLOADS_FOLDER "/Downloads"
#endif  // REMM_DOWNLOADS_FOLDER

#ifndef REMM_PROFILE_FILE_NAME
    #define REMM_PROFILE_FILE_NAME "/profile.json"
#endif  // REMM_PROFILE_FILE_NAME

#ifndef REMM_MODS_STAGING_FILE_NAME
    #define REMM_MODS_STAGING_FILE_NAME "/mods_staging.json"
#endif  // REMM_MODS_STAGING_FILE_NAME

#ifndef REMM_MODS_INSTALLED_FILE_NAME
    #define REMM_MODS_INSTALLED_FILE_NAME "/mods_installed.json"
#endif  // REMM_MODS_INSTALLED_FILE_NAME

#ifndef REMM_GAME_NONE
    #define REMM_GAME_NONE "None"
#endif  // REMM_GAME_NONE

#ifndef REMM_GAME_MONSTER_HUNTER_RISE
    #define REMM_GAME_MONSTER_HUNTER_RISE "MonsterHunterRise"
#endif  // REMM_GAME_MONSTER_HUNTER_RISE

#ifndef REMM_CONF_PATCHES
    #define REMM_CONF_PATCHES "Patches"
#endif  // REMM_CONF_PATCHES

#ifndef REMM_CONF_GAMES
    #define REMM_CONF_GAMES "Games"
#endif  // REMM_CONF_GAMES

#ifndef REMM_CONF_GAME_PATH
    #define REMM_CONF_GAME_PATH "GamePath"
#endif  // REMM_CONF_GAME_PATH

#ifndef REMM_CONF_SELECTED_PROFILE
    #define REMM_CONF_SELECTED_PROFILE "SelectedProfile"
#endif  // REMM_CONF_SELECTED_PROFILE

#ifndef REMM_CONF_LAST_SELECTED_GAME
    #define REMM_CONF_LAST_SELECTED_GAME "LastSelectedGame"
#endif  // REMM_CONF_LAST_SELECTED_GAME

#ifndef REMM_CONF_PATCH_RE_ENGINE_PAK_INDEX
    #define REMM_CONF_PATCH_RE_ENGINE_PAK_INDEX "PatchReEnginePakIndex"
#endif  // REMM_CONF_PATCH_RE_ENGINE_PAK_INDEX

#endif  // REMODMAN_MANAGER_DEFINITIONS_INCLUDED
