#ifndef REMODMAN_MANAGER_DEFINITIONS_INCLUDED
#define REMODMAN_MANAGER_DEFINITIONS_INCLUDED

#pragma once

#ifndef REMM_MODS_FOLDER
    #define REMM_MODS_FOLDER "/Mods/"
#endif  // REMM_MODS_FOLDER

#ifndef REMM_DOWNLOADS_FOLDER
    #define REMM_DOWNLOADS_FOLDER "/Downloads"
#endif  // REMM_DOWNLOADS_FOLDER

#ifndef REMM_PROFILE_FILE_NAME
    #define REMM_PROFILE_FILE_NAME "/profile.json"
#endif  // REMM_PROFILE_FILE_NAME

#ifndef REMM_MODS_STAGING_FILE_NAME
    #define REMM_MODS_STAGING_FILE_NAME "/mods_staging.json"
#endif  // REMM_MODS_STAGING_FILE_NAME

#ifndef REMM_MODS_INSTALLED_FILE_NAME
    #define REMM_MODS_INSTALLED_FILE_NAME "/mods_installed.json"
#endif  // REMM_MODS_INSTALLED_FILE_NAME

#ifndef REMM_GAME_NONE
    #define REMM_GAME_NONE "None"
#endif // REMM_GAME_NONE

#ifndef REMM_GAME_MONSTER_HUNTER_RISE
    #define REMM_GAME_MONSTER_HUNTER_RISE "MonsterHunterRise"
#endif // REMM_GAME_MONSTER_HUNTER_RISE

#endif  // REMODMAN_MANAGER_DEFINITIONS_INCLUDED
