#ifndef REMODMAN_MANAGER_DEFINITIONS_INCLUDED
#define REMODMAN_MANAGER_DEFINITIONS_INCLUDED

#pragma once

#ifndef MODS_FOLDER
#define MODS_FOLDER "/Mods/"
#endif // MODS_FOLDER

#ifndef DOWNLOADS_FOLDER
#define DOWNLOADS_FOLDER "/Downloads"
#endif // DOWNLOADS_FOLDER

#ifndef PROFILE_FILE_NAME
#define PROFILE_FILE_NAME "/profile.json"
#endif // PROFILE_FILE_NAME

#ifndef MODS_STAGING_FILE_NAME
#define MODS_STAGING_FILE_NAME "/mods_staging.json"
#endif // MODS_STAGING_FILE_NAME

#ifndef MODS_INSTALLED_FILE_NAME
#define MODS_INSTALLED_FILE_NAME "/mods_installed.json"
#endif // MODS_INSTALLED_FILE_NAME

#endif // REMODMAN_MANAGER_DEFINITIONS_INCLUDED
